baseURL = "https://blog.pbcompaan.tk/"
languageCode = "en-us"
title = "Blog"
theme = "kiera"

[author]
name = "Pepijn Compaan"
github = "PretentiousPotatoPeeler"
linkedin = "pepijn-compaan-b97623121"

[params]
tagline = "Stuff I've Figured Out"
